# Generated by Django 4.2 on 2024-08-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='total_goals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='total_play_time',
            field=models.FloatField(default=0),
        ),
    ]
