# Generated by Django 4.2 on 2024-08-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0003_remove_player_total_goals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='type',
            field=models.CharField(choices=[('CREATED', 'Criado'), ('AWAITING_CONFIRMATION', 'Aguardando Confirmação'), ('IN_PROGRESS', 'Em Progresso'), ('FINISHED', 'Finalizado'), ('CANCELLED', 'Cancelado')], default='MULTIPLAYER_ONLINE', max_length=100),
        ),
    ]
